// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPLYLb4NfmySsi0VszSXbQCv-7zK8MyTE',
    appId: '1:651485111989:web:99bf77fee78925403ac0fc',
    messagingSenderId: '651485111989',
    projectId: 'flight-project-3f9bb',
    authDomain: 'flight-project-3f9bb.firebaseapp.com',
    storageBucket: 'flight-project-3f9bb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOMyMNx9i0_rzRuM2HJzZlju6Y9LULbdY',
    appId: '1:651485111989:android:2033849a3fbab6af3ac0fc',
    messagingSenderId: '651485111989',
    projectId: 'flight-project-3f9bb',
    storageBucket: 'flight-project-3f9bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu_0yNw6JAqYK5vMQAO3Gtchbwrkx0hmw',
    appId: '1:651485111989:ios:a4820b6ae4b67a523ac0fc',
    messagingSenderId: '651485111989',
    projectId: 'flight-project-3f9bb',
    storageBucket: 'flight-project-3f9bb.appspot.com',
    iosBundleId: 'com.example.flightApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu_0yNw6JAqYK5vMQAO3Gtchbwrkx0hmw',
    appId: '1:651485111989:ios:7de25b38dfeec4c83ac0fc',
    messagingSenderId: '651485111989',
    projectId: 'flight-project-3f9bb',
    storageBucket: 'flight-project-3f9bb.appspot.com',
    iosBundleId: 'com.example.flightApp.RunnerTests',
  );
}
